// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWlLmgnrWrYMVgAbCs3IgSfIBvufDwVLQ',
    appId: '1:159434246863:ios:63cb81ff46bfd12a2a05ba',
    messagingSenderId: '159434246863',
    projectId: 'gestion-b8736',
    storageBucket: 'gestion-b8736.firebasestorage.app',
    iosBundleId: 'com.example.gestionApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqEhigf8bVoGWSte1gwsOxNgiMuCbcFcs',
    appId: '1:159434246863:web:ab668785493c4d1a2a05ba',
    messagingSenderId: '159434246863',
    projectId: 'gestion-b8736',
    authDomain: 'gestion-b8736.firebaseapp.com',
    storageBucket: 'gestion-b8736.firebasestorage.app',
    measurementId: 'G-ZBWXG876DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZk2OO99BgJrqq5QdB4jYHl9ExN0GzLiI',
    appId: '1:159434246863:android:d38ac9b188cd4f162a05ba',
    messagingSenderId: '159434246863',
    projectId: 'gestion-b8736',
    storageBucket: 'gestion-b8736.firebasestorage.app',
  );

}